# Generated by Django 5.2.5 on 2025-08-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_playlist_songs_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
