# Generated by Django 5.2.5 on 2025-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='artist_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emotion_stats',
            field=models.JSONField(default=dict),
        ),
    ]
