# Generated by Django 5.2.5 on 2025-08-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_artist_stats_userprofile_emotion_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='emotion',
            field=models.CharField(blank=True, choices=[('Happiness', 'Happiness'), ('Sadness', 'Sadness'), ('Calmness', 'Calmness'), ('Excitement', 'Excitement'), ('Love', 'Love')], max_length=20, null=True),
        ),
    ]
