# Generated by Django 5.2.5 on 2025-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_song_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portrait_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
