# Generated by Django 5.2.5 on 2025-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_portrait_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Urdu', 'Urdu'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_stats',
            field=models.JSONField(default=dict),
        ),
    ]
